# Generated by Django 3.2.4 on 2021-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/avatars/default.jpg', upload_to='avatars'),
        ),
    ]
